# Generated by Django 3.2.12 on 2022-05-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_alter_course_daraja'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='a'),
        ),
    ]
